// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: images.sql

package database

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images(user_id , file_name , file_size , storage_url) VALUES ($1,$2,$3,$4)RETURNING file_name , file_size , storage_url
`

type CreateImageParams struct {
	UserID     int64
	FileName   string
	FileSize   int64
	StorageUrl string
}

type CreateImageRow struct {
	FileName   string
	FileSize   int64
	StorageUrl string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (CreateImageRow, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.UserID,
		arg.FileName,
		arg.FileSize,
		arg.StorageUrl,
	)
	var i CreateImageRow
	err := row.Scan(&i.FileName, &i.FileSize, &i.StorageUrl)
	return i, err
}
