// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type User struct {
	UserID            int64
	FullName          string
	Password          string
	Email             string
	CreatedAt         time.Time
	PasswordChangedAt time.Time
}
