// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(full_name , password , email) VALUES ($1,$2,$3) RETURNING full_name ,email
`

type CreateUserParams struct {
	FullName string
	Password string
	Email    string
}

type CreateUserRow struct {
	FullName string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FullName, arg.Password, arg.Email)
	var i CreateUserRow
	err := row.Scan(&i.FullName, &i.Email)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id , full_name , email FROM users WHERE user_id=$1
`

type GetUserByIDRow struct {
	UserID   int64
	FullName string
	Email    string
}

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(&i.UserID, &i.FullName, &i.Email)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT user_id , full_name , email FROM users LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32
	Offset int32
}

type GetUsersRow struct {
	UserID   int64
	FullName string
	Email    string
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(&i.UserID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
